# Development-specific configuration
spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: true
        
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      
  data:
    redis:
      host: localhost
      port: 6379
      
logging:
  level:
    com.userservice: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    include-stacktrace: on-param
    include-message: always

# Custom application properties
app:
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000
  cache:
    enabled: true
    default-ttl: 300 # 5 minutes for dev
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always